name: Git Actions Self Demo
# The workflow / CI server runs / triggers when there is a push to the repo, do dashes for multiple trigger requirements 
on: [push]
#what jobs do we want as part of our workflow 
jobs: 
  actions_demo: 
   runs-on: ubuntu-latest # Creating a container (virtual machine) that uses ubuntu
   # What do we want this machine to do? 
   steps:
   - run: echo "Hello World!"
   - run: pwd
   - run: ls -a 
   - run: touch hello.txt
   - run: echo "Hello world" >> hello.txt
   - run: cat *
   - run: whoami
